language: php

php:
	- 5.3
  	- 5.4

script: php vendor/bin/phpunit -c tests/phpunit.xml --verbose --coverage-text tests/

before_script:
	- "curl -s http://getcomposer.org/installer | php"
    - "php composer.phar install --dev --verbose"

after_script:
  - "php vendor/bin/phpunit -c tests/phpunit.xml --testdox tests/"