language: php
script: php vendor/bin/phpunit -c tests/phpunit.xml --verbose --coverage-text tests/

php:
	- 5.3
  	- 5.4

before_script:
    - "composer install --dev --verbose"

after_script:
  - "php vendor/bin/phpunit -c tests/phpunit.xml --testdox tests/"