language: php
script: php vendor/phpunit/phpunit/composer/bin/phpunit -c tests/phpunit.xml --verbose --coverage-text tests/CiCodeGeneratorTest.php

php:
  - 5.3
  - 5.4

before_script:
  - "git clone --branch=developer --depth=100 --quiet git://github.com/EllisLab/CodeIgniter.git willmendesneto/codeigniter"
  - "cp -R willmendesneto/codeigniter/ ../"
  - "rm -rf codeigniter"
  - "curl -s http://getcomposer.org/installer | php"
  - "php composer.phar --dev install"

after_script:
  - "php vendor/phpunit/phpunit/composer/bin/phpunit -c tests/phpunit.xml --testdox tests/CiCodeGeneratorTest.php"
