language: php
script: php vendor/phpunit/phpunit/composer/bin/phpunit -c tests/phpunit.xml --verbose --coverage-text tests/CiCodeGeneratorTest.php

php:
  - 5.3
  - 5.4

before_script:
  - "git clone git://github.com/EllisLab/CodeIgniter.git codeigniter"
  - "cp -R willmendesneto/codeigniter/* ../willmendesneto/"
  - "rm -rf codeigniter"
  - "curl -s http://getcomposer.org/installer | php"
  - "php composer.phar --dev install"

after_script:
  - "php vendor/phpunit/phpunit/composer/bin/phpunit -c tests/phpunit.xml --testdox tests/CiCodeGeneratorTest.php"
