language: php
script: php vendor/phpunit/phpunit/composer/bin/phpunit --verbose --coverage-text tests/CiCodeGeneratorTest.php

php:
  - 5.3
  - 5.4

before_script:
  - "curl -s http://getcomposer.org/installer | php"
  - "php composer.phar --dev install"

after_script:
  - "php vendor/phpunit/phpunit/composer/bin/phpunit --testdox tests/CiCodeGeneratorTest.php"