language: php
script: php vendor/phpunit/phpunit/composer/bin/phpunit -c tests/phpunit.xml --verbose --coverage-text tests/CiCodeGeneratorTest.php

php:
  - 5.3
  - 5.4

before_script:
  - "git clone --branch=master git://github.com/EllisLab/CodeIgniter.git /home/travis/builds/willmendesneto/CI-Code-Generator/codeigniter"
  - "cp -R /home/travis/builds/willmendesneto/CI-Code-Generator/codeigniter/* /home/travis/builds/willmendesneto/CI-Code-Generator/"
  - "rm -rf /home/travis/builds/willmendesneto/CI-Code-Generator/codeigniter/"
  - "curl -s http://getcomposer.org/installer | php"
  - "php composer.phar --dev install"

after_script:
  - "php vendor/phpunit/phpunit/composer/bin/phpunit -c tests/phpunit.xml --testdox tests/CiCodeGeneratorTest.php"
